export { default as hlim } from './hlim'
export { default as identity } from './identity'
export { default as logistic } from './logistic'
export { default as relu } from './relu'
export { default as tanh } from './tanh'
